### ISSUE TITLE
Scout Test App Missing reference

### ISSUE THREAD

**Issue by jonweaver** [OkumaAmerica/Open-API-SDK#19]
The Scout test application has a reference to the Okuma.Scout dll that is not part of the public repo. Should the DLL be in a separate directory under Scout?

**Comment by OkumaScott** [comment]
Fixed.

**Comment by jonweaver** [comment]
I see that the reference path is updated but the actual file is not in repo.  Is it a .gitignore issue? 

![image](https://user-images.githubusercontent.com/18248207/46756974-c8c03300-cc96-11e8-9e30-10dc053d86d3.png)

**Comment by OkumaScott** [comment]
You're right, the gitignore was not letting the compiled libraries get uploaded. Should be fixed now. :crossed_fingers:
