### ISSUE TITLE
SubSystemEnum Enumeration 2SP Gantry Load

### ISSUE THREAD

**Issue by m-ash101** [OkumaAmerica/Open-API-SDK#32]
I am writing an application to interface with a customer's 2SP lathe that has gantry load.  I need to read and write to the common variables on the gantry "channel" of the control. I am familiar with writing to the right/left spindle common variables by setting the SubSystemEnum to NC_AL/NC_2AL.   objVariables.SetSubSystem(enSubSystem:=Okuma.CLDATAPI.Enumerations.SubSystemEnum.NC_2AL)
**Is there a subsystem enumeration that will allow me to read/write to the gantry channel?**  
There is nothing in the documentation for the lathe API that refers to anything about gantry or OGL interfacing.
The only possibility I see is NC_RUN enumeration, but that looks like it depends on what the user has brought up on the OSP control.

Any information is appreciated.

**Comment by hulinning2** [comment]
gantry loader cannot be supported yet
Thanks
