### ISSUE TITLE
.NET version requirements per API version to the readme file

### ISSUE THREAD

**Issue by ssolmer** [OkumaAmerica/Open-API-SDK#6]
e.g.
├───API		      /* Recommended API versions for development */
│   ├───1.9.1  (requires .NET 1.1 available from https://goo.gl/5V3c44)
│   │   ├───Bin
|   |   ├───Help

Where 
    https://goo.gl/5V3c44
is a link to
    https://www.microsoft.com/en-us/download/details.aspx?id=26
that was shortened using
    https://goo.gl/
(one opposed to google tracking could just as effectively use any of
    https://bitly.com/
    http://tinyurl.com/
    http://ow.ly/url/shorten-url

> Originally created at 2016-11-02 14:00:59+00:00 (UTC) by okumatony as a(n) minor issue.

**Comment by OkumaScott** [comment]
Issues must be assigned in order to for Bitbucket to send email notifications.

**Comment by OkumaScott** [comment]
formatting on this proposal got lost. see email

**Comment by ssolmer** [comment]
Release Notes have been added to Open-API-SDK\Documentation\THINC API Release Notes.
This closes #6
